SELECT
  p.AMOUNT AS SALARY,
  CONCAT(e.FIRST_NAME, ' ', e.LAST_NAME) AS NAME,
  TIMESTAMPDIFF(YEAR, e.DOB, DATE(p.PAYMENT_TIME)) AS AGE,
  d.DEPARTMENT_NAME
FROM PAYMENTS p
JOIN EMPLOYEE  e ON e.EMP_ID = p.EMP_ID
JOIN DEPARTMENT d ON d.DEPARTMENT_ID = e.DEPARTMENT
WHERE DAY(p.PAYMENT_TIME) <> 1
ORDER BY p.AMOUNT DESC, p.PAYMENT_TIME DESC, p.PAYMENT_ID DESC
LIMIT 1;
